### ISSUE TITLE
Milestone 2.1 Housekeeping

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#105]
# Description

Small housekeeping issues in milestone 2.1

# Related Issues
- [ ] Forgot password api guide SkygearIO/guides#111
- [ ] JS cloud code SkygearIO/guides#119
- [ ] Take down credential in screenshots of quick start SkygearIO/guides#40
- [ ] Update Access Control Basics and add guides for field-based ACL SkygearIO/guides#76

**Comment by chpapa** [comment]
actually if it is a relative simple guide maybe can just have an issue in skygeario/guides and include that issue in housekeeping feature issue of milestone 2.1

**Comment by carmenlau** [comment]
@chpapa Sure! I think the housekeeping feature issue of 2.1 is not opened yet? Let me rename this issue to that :P

**Comment by chpapa** [comment]
Great :-)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: carmenlauSent: Wednesday, 13 September, 2017 12:01 PMTo: SkygearIO/featuresReply To: SkygearIO/featuresCc: Ben Cheng; MentionSubject: Re: [SkygearIO/features] Forget password api guide (#105)@chpapa Sure! I think the housekeeping feature issue of 2.1 is not opened yet? Let me rename this issue to that :P

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SkygearIO/features","title":"SkygearIO/features","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SkygearIO/features"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carmenlau in #105: @chpapa Sure! I think the housekeeping feature issue of 2.1 is not opened yet? Let me rename this issue to that :P"}],"action":{"name":"View Issue","url":"https://github.com/SkygearIO/features/issues/105#issuecomment-329052599"}}}
