### ISSUE TITLE
Password policy setting for security audit

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#154]
# Tasks
- [x] Skygear server update to adopt password checking
- [X] Update portal to have UI for password policy configuration #150 
- [X] Password policy errors handling https://github.com/SkygearIO/skygear-server/commit/f79c5d3c8eda39e801acf7649c872a922b5298ee

# Portal Design
- [x] Page for user to update password setting

**Comment by carmenlau** [comment]
All feature completed, will close after deployment

**Comment by carmenlau** [comment]
It is available in production already. I think the setup is simple in portal. See if we need a guide for it? @chpapa @tensiuyan

**Comment by chpapa** [comment]
@tensiuyan the portal is trivial, I think the only guide needed is to explain to developer how they should handle error due to password policy.

**Comment by carmenlau** [comment]
Password policy guide deployed: https://docs.skygear.io/guides/auth/password-policy/ios/
