### ISSUE TITLE
Other P1/P2 issues

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#214]
# Description

This is a meta tracking issue for other priority 1 issues:

* [x] skygeario/py-skygear#196 Database Hooks param `async` is reserved word in Python 3.7
* ~skygeario/chat-SDK-JS#100 All api that accept array of objects should also allow passing array of ids~
* [ ] oursky/skygear-cloud#490 Avoid restart of Skygear pod when CMS config updated
* [ ] skygeario/skygear-server#452 Schema migration is expected to happen after `before_save`

Priority 2:

* [ ] skygeario/skygear-server#560 profile memory usage for memory leak

**Comment by carmenlau** [comment]
We will plan to do `async` param update first, as this is one of the features that will have breaking change.
