### ISSUE TITLE
2.0 Launch Miscellaneous

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#392]
Miscellaneous work to launch 2.0

## Website
* [x] add 'Join beta' on skygear.io and link to sign up form
* [x] add Pricing on Skygear.io (depends on design: https://3.basecamp.com/3096882/buckets/11477446/todos/2093853450)
* [x] sign up Slack alert oursky/skygear-controller#212

## Distribution
* [x] deprecate JS SDK v1 #202
* [x] deprecate skycli #201

## Developments
* [x] Update all repos branch from next to master, notify ben when this is done for updating skygear-server readme
