### ISSUE TITLE
GeoJSON Support

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#49]
# Description

Support GeoPolygon and Location storage, search by location and search by geometry.

# API Design

## Scenario

**Put list of Scenario how developers will use this API**

### To save polygon
```
const polygon = new skygear.GeoJSON({
  "type": "Polygon",
  "coordinates": [[
    [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]
  ]]
});
```

### To search geometry by location
```
const query = new skygear.Query(District);
const geoLocation = new skygear.Geolocation(22.283, 114.15);
query.containsValue('area', geoLocation);
```

### To search location by geometry
```
const place = new Place({
  name: 'IFC HK',
  location: geoLocation,
});
skygear.publicDB.save(place);

const query = new skygear.Query(Place)
query.contains('location', polygon); 
```

### To search geometry by geometry
```
const query = new skygear.Query(District);
query.containsValue('area', polygon);
```

### Other geometry types

http://geojson.org/geojson-spec.html#appendix-a-geometry-examples

### Point
```
{
  "type": "Point", 
  "coordinates": [102.0, 0.5]
}
```

### LineString
```
{
  "type": "LineString",
  "coordinates": [
    [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
  ]
}
```

### Polygon with interior rings
```
{ "type": "Polygon",
  "coordinates": [
    [[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
    [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]
  ]
}
```

### Multipolygon
```
{ "type": "MultiPolygon",
  "coordinates": [
    [[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]],
    [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]],
     [[100.2, 0.2], [100.8, 0.2], [100.8, 0.8], [100.2, 0.8], [100.2, 0.2]]]
    ]
}
```
## API Design

**Put Design and Specification here with links**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues 
  - [x] skygeario/skygear-server#262
  - [ ] skygeario/skygear-server#343
- Client Issues
  - [ ] SkygearIO/skygear-SDK-Android#121
  - [ ] skygeario/skygear-SDK-JS#185
  - [ ] SkygearIO/skygear-SDK-iOS#90
  - [ ] SkygearIO/py-skygear#133
- Guides Issues
  - [ ] SkygearIO/guides#50

# Progress Tracker

- [x] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code SkygearIO/skygear-server#340
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by rickmak** [comment]
@chpapa Do we want a committed HTTP request sample in this issue and put up a documentation?

**Comment by chpapa** [comment]
Sounds like a good idea. Maybe keep it under a wiki page and link from repo?

**Comment by chpapa** [comment]
> Do we want a committed HTTP request sample in this issue and put up a documentation?
@rickmak sounds like a good idea.

**Comment by rickmak** [comment]
@chpapa I revive the old protocol draft here: https://github.com/SkygearIO/skygear-server/wiki/Protocol-Auth

It should be outdated. I just put up for editing.

**Comment by chpapa** [comment]
@rickmak can you check if this feature already got minimal tests and API docs? If yes can you check the two box and put this label workflow to code-complete?

cc: @cheungpat
