### ISSUE TITLE
SDK API Grouping

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/features#70]
# Description

Following a discussion from skygeario/skygear-SDK-JS#220,

* A `Container` class that exposes all API.
* The API have to be discoverable by the app developer, probably by way of looking at class doc, or through IDE autocompletion.
* The API have to be grouped into feature-set so that app developer can find an API by narrowing down to the set of API via the grouping. Grouping is achieved by way of putting API of the same feature-set into a separate class to be exposed by the `Container`.
* The API exposed by all languages SDK have to be the same, meaning the same set of API has to be available within the same grouping and exposed via similar mechanisms.
* The API organization is totally app-developer-driven, so how the plugin code is organized doesn’t matter.

# API Design

> Note: this is not real code, do not copy from these code, these are for illustration purpose only.

```objective-c
// Objective-C
#import <SKYKit/SKYKit.h>

SKYContainer *container = [SKYContainer defaultContainer];
[container.auth loginWithEmail:@"email@example.com" password:@"secret" completion:nil];
[container.auth forgotPasswordWithEmail:@"email@example.com" completion:nil];
[container.pubsub subscribeTo:"channel" handler:nil];
```

```java
// Java
import android.content.Context;
import io.skygear.skygear.Container;
import io.skygear.skygear.Pubsub;

Container container = Container.defaultContainer(Context.getApplicationContext());
container.auth.loginWithEmail("email@example.com", "secret");
container.auth.forgotPassword("email@example.com");
container.pubsub.subscribe("channel", new Pubsub.Handler())
```

```javascript
// JS
var skygear = require('skygear');

skygear.auth.loginWithEmail("email@example.com", "secret");
skygear.auth.forgotPassword("email@example.com");
skygear.pubsub.on("channel", function() {});
```

# Open Questions

* What are the list of groupings? (e.g. `auth`, `pubsub`, `db`)
* How the existing APIs are grouped?
* When we roll out the change (i.e. when API are grouped), do we maintain backward compatibility?

IMO these questions are best answered by @chpapa who has better understanding of what cloud developer needs. The grouping are especially important as we need a grouping that makes sense to cloud developer as well as making them future proof when we need to add more APIs in the future.

When we have a list of grouping. I will try to group the existing the APIs and see if everyone agrees on them.

# Related Issues

- Client Issues
  - [ ] SkygearIO/skygear-SDK-JS#231
  - [ ] SkygearIO/skygear-SDK-iOS#104
  - [ ] SkygearIO/skygear-SDK-Android#133
- Guides Issues
  - [ ] SkygearIO/guides#78

# Progress Tracker

- [x] Specification Design Approval
- [x] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [x] Code
  - [x] Minimal tests
  - [x] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
Thanks a lot @cheungpat Yes I agree with the direction. Sorry I wasn't able to work on it in more details yet. So please try to go ahead with the design if possible.

On the marketing level, we currently market in the following features (e.g. we group documentation based on these)
* Cloud DB
* Auth
* Chat
* Push
* Pubsub
* CMS
* Cloud Functions

The tricky thing is, do we want to set a standard for other minor plugins? For example, Louis has made an event tracking #33.

Why I said it is tricky, is because: why chat / event-tracker doesn't belong to Container, while Cloud DB / Auth / Pubsub / Cloud Functions are? To put it more concrete, why we have this:

```javascript
skygear.auth.loginWithEmail()
skygear.pubsub.on()
skygear.publicDB.query()

skygearChat.createConversation() // or shall we have skygear.chat.createConversation()?
```

instead of this?

```javascript
skygearAuth.loginWithEmail()
skygearPubsub.on()
skygearDB.public.query()
skygearChat.createConversation()
```

@rickmak @ben181231 thought?

**Comment by cheungpat** [comment]
@chpapa  `Container` currently serves as a context for client requests. The reason having auth/db/pubsub API on `Container` is merely of convenience because all the data is already there. We used to have an idea on grouping functionality by core/non-core so that functionality that we think developer needs the most will go into core, and hence the `Container`.

The simplest answer to “what goes into Container” is that almost nothing should go into `Container`. This rule is simpler for both app-developer and skygear-developer to follow, IMO.

Here is an alternative how the code would look based on @chpapa’s `skygearAuth.loginWithEmail()` idea.

# API Design

> Note: this is not real code, do not copy from these code, these are for illustration purpose only.

```objective-c
// Objective-C
#import <SKYKit/SKYKit.h>

SKYAuth *auth = [SKYAuth sharedInstance];
[auth loginWithEmail:@"email@example.com" password:@"secret" completion:nil];
SKYEventTracking *track = [SKYEventTracking sharedInstance]; // same as above
[track trackAction:"login"];
```

```java
// Java
import android.content.Context;
import io.skygear.skygear.Container;
import io.skygear.skygear.Auth;

Auth auth = new Auth(Context.getApplicationContext()); // or Auth(Container.defaultContainer(Context.getApplicationContext()));
auth.loginWithEmail("email@example.com", "secret");
EventTracking track = new EventTracking(Context.getApplicationContext());
track.trackAction("login");
```

```javascript
// JS
var skygearAuth = require('skygear/auth');
var skygearTracking = require('skygear-event-tracking');
// or perhaps,
var {skygearAuth, skygearTracking} = require('skygear');

skygearAuth.loginWithEmail("email@example.com", "secret");
skygearTracking.track("login");
```

**Comment by rickmak** [comment]
`skygearAuth.loginWithEmail()` way is current way of plugin organization. You may take a look at `skygearChat`. I think the discussion in forgot password concluding the idea of `core` is fluid and changing. So the current separation will no longer make sense. i.e. `Container` will no longer holding `core` things. Instead, we group them by `logical`(to marketing angle or whatever angle). Just be logical(to the user) on usage level will be fine for me.

### `skygear.auth` vs `skygearAuth`

`skygear.auth` is what we discuss previously and everyone happy with it. I assume we have to commit a standard interface for 3rd party developer to inject their namespace dynamically. Which we need to a proper design and sure it is workable and easy to use.

For `skygearAuth`, we are deferring the DI responsibility to plugin developer. Which I think not desired by @chpapa, IMO.

**Comment by chpapa** [comment]
skygear.auth
skygear.db.public
skygear.db.private
skygear.chat
skygear.push
skygear.pubsub
skygear.cloudfunc
skygear.analytics

**Comment by Steven-Chan** [comment]
I have a question: should the groups be stateful or stateless, i.e. just collections of functions? Or maybe some states are held by group while some held by the `Container` itself. 

Use auth as example.

For current implementation, the `Container` object is storing `accessToken`, `currentUser` and `apiKey`. It means that the context of `Container` includes the current app, and the current user.

I expect after API Grouping is done, the `login` function would be under the `auth` group. My question is, **should the current user be stored in the `auth` group, or remains in `Container`**.

I am not really familiar with the source code, but as I look at the container class quickly, besides `apiKey`, the user auth state and db cache are most likely to be moved to their own group.

If using the stateful group approach, `Container` would be as clean as possible, which I think is the goal of this issue. But some, actually a lot, of the group would be required to depend on the auth state. Then, the groups would have dependencies with each other.

**Comment by chpapa** [comment]
Just my 2 cents below...

> I am not really familiar with the source code, but as I look at the container class quickly, besides apiKey, the user auth state and db cache are most likely to be moved to their own group.

@Steven-Chan Seems you have an opinion already.

> But some, actually a lot, of the group would be required to depend on the auth state. Then, the groups would have dependencies with each other.

Maybe it still makes sense to have some common functions (e.g. `makeRequest()`) and data (e.g. `currentUser`) in `Container`, to avoid modules calling each other directly and have too high coupling in future.

**Comment by seventhmoon** [comment]
While doing on mobile (aka building for next billion), we tried to make things small.
Just like in Android, support library and google play services are now break down into modules and developer select only modules they want.

Although data is already there in the container. Should being lite also a direction for the SDK?

**Comment by chpapa** [comment]
> Although data is already there in the container. Should being lite also a direction for the SDK?

We don't want to break modules too small to make things difficult to comprehend for a new user. But I think somehow breaking a single `Container` into `skygear.auth` / `skygear.db` / `skygear.pubsub` etc... is a reasonable first step? In future, we can let users pick the modules they need (like `skygear.chat`)

**Comment by Steven-Chan** [comment]
> While doing on mobile (aka building for next billion), we tried to make things small.
> Just like in Android, support library and google play services are now break down into modules and developer select only modules they want.
> 
> Although data is already there in the container. Should being lite also a direction for the SDK?

I think we need to make it clear here, since this would affect the implementation. I guess it may even affect the interface in Java.

Modules may have dependencies with each other, the most common use case is `db` require `auth`. Firebase treat this with pubsub. `auth` broadcasts events when user auth state changes, `db` subscribes to the events and updates it own state.

On the other hand, `db` can access `auth` directly. Code would be much simpler. But then I am not so sure how to achieve the `developer select only modules they want` in Java, with the previously proposed code.

```java
Container container = Container.defaultContainer(Context.getApplicationContext());
container.auth.loginWithEmail("email@example.com", "secret");
container.auth.forgotPassword("email@example.com");
container.pubsub.subscribe("channel", new Pubsub.Handler());
```

I can only think of reflection, or annotation with code generation, but would it be over-engineered?

**Comment by chpapa** [comment]
@Steven-Chan one side notes, when you separate the module, do you think we can make it easy to generate API docs for each module? (say an API doc for auth, pubsub, chat, push, etc) It is not a must but might make it easier for people to look for references.

**Comment by Steven-Chan** [comment]
I expect a clearer doc can be generated, since `Container` would no longer have a long list of functions, and the list of module would be shown on the class list, and a summary of the module can be included in the doc.

**Comment by rickmak** [comment]
> `developer select only modules they want`

I am not sure this is the main goal of this issue. I think it is nice to have only. At least for __core__ or common feature. I don't expect they can use `db` without auth. Or `liveupdate`(if we have in future) without `pubsub`.

I think the more valid problem of `access auth directly` or `auth broadcasts events` is: Are we going to support multiple skygear app in one mobile app context. Firebase support it. Currently Skygear don't support it. It will affect how the access/broadcast to be done if we decided to support multiple instance.

**Comment by chpapa** [comment]
> Currently Skygear don't support it. It will affect how the access/broadcast to be done if we decided to support multiple instance.

That's a very interesting question. If it won't make the proposal too complicated, I would love to see if we can support multiple instances. I guess down the road we will need it so if we can just get it right once here we can avoid another big revamp in future.

**Comment by Steven-Chan** [comment]
I think multiple instance can be achieved as long as it is not hard coded to get the default skygear container instance.

For https://github.com/SkygearIO/features/pull/71, I would expect all sub-containers to be created when the skygear container get created, which is where the container would be passed to the sub-containers.

**Comment by chpapa** [comment]
@rickmak @Steven-Chan yesterday we discussed slightly said it should be `skygear.publicDB` instead of `skygear.db.public`, and `skygear.auth.sso`? is that agreed and if yes it shall reflect on the feature spec?

**Comment by cheungpat** [comment]
@Steven-Chan you should also create an issue for updating the guides.
